const mongoose = require('mongoose');

const schoolSchema = new mongoose.Schema({
  LEAID: { type: Number, required: true },
  SCHID: { type: Number, required: true },
  SCH_NAME: { type: String, required: true },
  COMBOKEY: { type: Number, required: true },
  TOT_ENR: { type: Number, required: true },
  TOT_ENR_M: { type: Number, required: true },
  TOT_ENR_F: { type: Number, required: true },
  SCH_ENR_LEP: { type: Number, required: true },
  SCH_ENR_LEP_M: { type: Number, required: true },
  SCH_ENR_LEP_F: { type: Number, required: true },
  SCH_ENR_IDEA: { type: Number, required: true },
  SCH_ENR_IDEA_M: { type: Number, required: true },
  SCH_ENR_IDEA_F: { type: Number, required: true },
  SCH_ENR_AM_M: { type: Number, required: true },
  SCH_ENR_AM_F: { type: Number, required: true },
  SCH_ENR_AS_M: { type: Number, required: true },
  SCH_ENR_AS_F: { type: Number, required: true },
  SCH_ENR_BL_M: { type: Number, required: true },
  SCH_ENR_BL_F: { type: Number, required: true },
  SCH_ENR_HI_M: { type: Number, required: true },
  SCH_ENR_HI_F: { type: Number, required: true },
  SCH_ENR_PI_M: { type: Number, required: true },
  SCH_ENR_PI_F: { type: Number, required: true },
  SCH_ENR_TR_M: { type: Number, required: true },
  SCH_ENR_TR_F: { type: Number, required: true },
  SCH_ENR_WH_M: { type: Number, required: true },
  SCH_ENR_WH_F: { type: Number, required: true },
  DISABILITIES: {
    AUT: {
      DISABILITY_CATEGORY: { type: String, required: true },
      TOTAL_STUDENTS_REPORTED: { type: Number, required: true },
      TOT_ENR_M: { type: Number, required: true },
      TOT_ENR_F: { type: Number, required: true },
      AM_M_7: { type: Number, required: true },
      AS_M_7: { type: Number, required: true },
      BL_M_7: { type: Number, required: true },
      HI_M_7: { type: Number, required: true },
      PI_M_7: { type: Number, required: true },
      TR_M_7: { type: Number, required: true },
      WH_M_7: { type: Number, required: true },
      AM_F_7: { type: Number, required: true },
      AS_F_7: { type: Number, required: true },
      BL_F_7: { type: Number, required: true },
      HI_F_7: { type: Number, required: true },
      PI_F_7: { type: Number, required: true },
      TR_F_7: { type: Number, required: true },
      WH_F_7: { type: Number, required: true },
    },
    DB: {
      DISABILITY_CATEGORY: { type: String, required: true },
      TOTAL_STUDENTS_REPORTED: { type: Number, required: true },
      TOT_ENR_M: { type: Number, required: true },
      TOT_ENR_F: { type: Number, required: true },
      AM_M_7: { type: Number, required: true },
      AS_M_7: { type: Number, required: true },
      BL_M_7: { type: Number, required: true },
      HI_M_7: { type: Number, required: true },
      PI_M_7: { type: Number, required: true },
      TR_M_7: { type: Number, required: true },
      WH_M_7: { type: Number, required: true },
      AM_F_7: { type: Number, required: true },
      AS_F_7: { type: Number, required: true },
      BL_F_7: { type: Number, required: true },
      HI_F_7: { type: Number, required: true },
      PI_F_7: { type: Number, required: true },
      TR_F_7: { type: Number, required: true },
      WH_F_7: { type: Number, required: true },
    },
    EMN: {
      DISABILITY_CATEGORY: { type: String, required: true },
      TOTAL_STUDENTS_REPORTED: { type: Number, required: true },
      TOT_ENR_M: { type: Number, required: true },
      TOT_ENR_F: { type: Number, required: true },
      AM_M_7: { type: Number, required: true },
      AS_M_7: { type: Number, required: true },
      BL_M_7: { type: Number, required: true },
      HI_M_7: { type: Number, required: true },
      PI_M_7: { type: Number, required: true },
      TR_M_7: { type: Number, required: true },
      WH_M_7: { type: Number, required: true },
      AM_F_7: { type: Number, required: true },
      AS_F_7: { type: Number, required: true },
      BL_F_7: { type: Number, required: true },
      HI_F_7: { type: Number, required: true },
      PI_F_7: { type: Number, required: true },
      TR_F_7: { type: Number, required: true },
      WH_F_7: { type: Number, required: true },
    },
    HI: {
      DISABILITY_CATEGORY: { type: String, required: true },
      TOTAL_STUDENTS_REPORTED: { type: Number, required: true },
      TOT_ENR_M: { type: Number, required: true },
      TOT_ENR_F: { type: Number, required: true },
      AM_M_7: { type: Number, required: true },
      AS_M_7: { type: Number, required: true },
      BL_M_7: { type: Number, required: true },
      HI_M_7: { type: Number, required: true },
      PI_M_7: { type: Number, required: true },
      TR_M_7: { type: Number, required: true },
      WH_M_7: { type: Number, required: true },
      AM_F_7: { type: Number, required: true },
      AS_F_7: { type: Number, required: true },
      BL_F_7: { type: Number, required: true },
      HI_F_7: { type: Number, required: true },
      PI_F_7: { type: Number, required: true },
      TR_F_7: { type: Number, required: true },
      WH_F_7: { type: Number, required: true },
    },
    MD: {
      DISABILITY_CATEGORY: { type: String, required: true },
      TOTAL_STUDENTS_REPORTED: { type: Number, required: true },
      TOT_ENR_M: { type: Number, required: true },
      TOT_ENR_F: { type: Number, required: true },
      AM_M_7: { type: Number, required: true },
      AS_M_7: { type: Number, required: true },
      BL_M_7: { type: Number, required: true },
      HI_M_7: { type: Number, required: true },
      PI_M_7: { type: Number, required: true },
      TR_M_7: { type: Number, required: true },
      WH_M_7: { type: Number, required: true },
      AM_F_7: { type: Number, required: true },
      AS_F_7: { type: Number, required: true },
      BL_F_7: { type: Number, required: true },
      HI_F_7: { type: Number, required: true },
      PI_F_7: { type: Number, required: true },
      TR_F_7: { type: Number, required: true },
      WH_F_7: { type: Number, required: true },
    },
    MISSING: {
      DISABILITY_CATEGORY: { type: String, required: true },
      TOTAL_STUDENTS_REPORTED: { type: Number, required: true },
      TOT_ENR_M: { type: Number, required: true },
      TOT_ENR_F: { type: Number, required: true },
      AM_M_7: { type: Number, required: true },
      AS_M_7: { type: Number, required: true },
      BL_M_7: { type: Number, required: true },
      HI_M_7: { type: Number, required: true },
      PI_M_7: { type: Number, required: true },
      TR_M_7: { type: Number, required: true },
      WH_M_7: { type: Number, required: true },
      AM_F_7: { type: Number, required: true },
      AS_F_7: { type: Number, required: true },
      BL_F_7: { type: Number, required: true },
      HI_F_7: { type: Number, required: true },
      PI_F_7: { type: Number, required: true },
      TR_F_7: { type: Number, required: true },
      WH_F_7: { type: Number, required: true },
    },
    MR: {
      DISABILITY_CATEGORY: { type: String, required: true },
      TOTAL_STUDENTS_REPORTED: { type: Number, required: true },
      TOT_ENR_M: { type: Number, required: true },
      TOT_ENR_F: { type: Number, required: true },
      AM_M_7: { type: Number, required: true },
      AS_M_7: { type: Number, required: true },
      BL_M_7: { type: Number, required: true },
      HI_M_7: { type: Number, required: true },
      PI_M_7: { type: Number, required: true },
      TR_M_7: { type: Number, required: true },
      WH_M_7: { type: Number, required: true },
      AM_F_7: { type: Number, required: true },
      AS_F_7: { type: Number, required: true },
      BL_F_7: { type: Number, required: true },
      HI_F_7: { type: Number, required: true },
      PI_F_7: { type: Number, required: true },
      TR_F_7: { type: Number, required: true },
      WH_F_7: { type: Number, required: true },
    },
    OHI: {
      DISABILITY_CATEGORY: { type: String, required: true },
      TOTAL_STUDENTS_REPORTED: { type: Number, required: true },
      TOT_ENR_M: { type: Number, required: true },
      TOT_ENR_F: { type: Number, required: true },
      AM_M_7: { type: Number, required: true },
      AS_M_7: { type: Number, required: true },
      BL_M_7: { type: Number, required: true },
      HI_M_7: { type: Number, required: true },
      PI_M_7: { type: Number, required: true },
      TR_M_7: { type: Number, required: true },
      WH_M_7: { type: Number, required: true },
      AM_F_7: { type: Number, required: true },
      AS_F_7: { type: Number, required: true },
      BL_F_7: { type: Number, required: true },
      HI_F_7: { type: Number, required: true },
      PI_F_7: { type: Number, required: true },
      TR_F_7: { type: Number, required: true },
      WH_F_7: { type: Number, required: true },
    },
    OI: {
      DISABILITY_CATEGORY: { type: String, required: true },
      TOTAL_STUDENTS_REPORTED: { type: Number, required: true },
      TOT_ENR_M: { type: Number, required: true },
      TOT_ENR_F: { type: Number, required: true },
      AM_M_7: { type: Number, required: true },
      AS_M_7: { type: Number, required: true },
      BL_M_7: { type: Number, required: true },
      HI_M_7: { type: Number, required: true },
      PI_M_7: { type: Number, required: true },
      TR_M_7: { type: Number, required: true },
      WH_M_7: { type: Number, required: true },
      AM_F_7: { type: Number, required: true },
      AS_F_7: { type: Number, required: true },
      BL_F_7: { type: Number, required: true },
      HI_F_7: { type: Number, required: true },
      PI_F_7: { type: Number, required: true },
      TR_F_7: { type: Number, required: true },
      WH_F_7: { type: Number, required: true },
    },
    SLD: {
      DISABILITY_CATEGORY: { type: String, required: true },
      TOTAL_STUDENTS_REPORTED: { type: Number, required: true },
      TOT_ENR_M: { type: Number, required: true },
      TOT_ENR_F: { type: Number, required: true },
      AM_M_7: { type: Number, required: true },
      AS_M_7: { type: Number, required: true },
      BL_M_7: { type: Number, required: true },
      HI_M_7: { type: Number, required: true },
      PI_M_7: { type: Number, required: true },
      TR_M_7: { type: Number, required: true },
      WH_M_7: { type: Number, required: true },
      AM_F_7: { type: Number, required: true },
      AS_F_7: { type: Number, required: true },
      BL_F_7: { type: Number, required: true },
      HI_F_7: { type: Number, required: true },
      PI_F_7: { type: Number, required: true },
      TR_F_7: { type: Number, required: true },
      WH_F_7: { type: Number, required: true },
    },
    SLI: {
      DISABILITY_CATEGORY: { type: String, required: true },
      TOTAL_STUDENTS_REPORTED: { type: Number, required: true },
      TOT_ENR_M: { type: Number, required: true },
      TOT_ENR_F: { type: Number, required: true },
      AM_M_7: { type: Number, required: true },
      AS_M_7: { type: Number, required: true },
      BL_M_7: { type: Number, required: true },
      HI_M_7: { type: Number, required: true },
      PI_M_7: { type: Number, required: true },
      TR_M_7: { type: Number, required: true },
      WH_M_7: { type: Number, required: true },
      AM_F_7: { type: Number, required: true },
      AS_F_7: { type: Number, required: true },
      BL_F_7: { type: Number, required: true },
      HI_F_7: { type: Number, required: true },
      PI_F_7: { type: Number, required: true },
      TR_F_7: { type: Number, required: true },
      WH_F_7: { type: Number, required: true },
    },
    TBI: {
      DISABILITY_CATEGORY: { type: String, required: true },
      TOTAL_STUDENTS_REPORTED: { type: Number, required: true },
      TOT_ENR_M: { type: Number, required: true },
      TOT_ENR_F: { type: Number, required: true },
      AM_M_7: { type: Number, required: true },
      AS_M_7: { type: Number, required: true },
      BL_M_7: { type: Number, required: true },
      HI_M_7: { type: Number, required: true },
      PI_M_7: { type: Number, required: true },
      TR_M_7: { type: Number, required: true },
      WH_M_7: { type: Number, required: true },
      AM_F_7: { type: Number, required: true },
      AS_F_7: { type: Number, required: true },
      BL_F_7: { type: Number, required: true },
      HI_F_7: { type: Number, required: true },
      PI_F_7: { type: Number, required: true },
      TR_F_7: { type: Number, required: true },
      WH_F_7: { type: Number, required: true },
    },
    VI: {
      DISABILITY_CATEGORY: { type: String, required: true },
      TOTAL_STUDENTS_REPORTED: { type: Number, required: true },
      TOT_ENR_M: { type: Number, required: true },
      TOT_ENR_F: { type: Number, required: true },
      AM_M_7: { type: Number, required: true },
      AS_M_7: { type: Number, required: true },
      BL_M_7: { type: Number, required: true },
      HI_M_7: { type: Number, required: true },
      PI_M_7: { type: Number, required: true },
      TR_M_7: { type: Number, required: true },
      WH_M_7: { type: Number, required: true },
      AM_F_7: { type: Number, required: true },
      AS_F_7: { type: Number, required: true },
      BL_F_7: { type: Number, required: true },
      HI_F_7: { type: Number, required: true },
      PI_F_7: { type: Number, required: true },
      TR_F_7: { type: Number, required: true },
      WH_F_7: { type: Number, required: true },
    },
  },
});
const School = mongoose.model('School', schoolSchema);

module.exports = School;
