const states = [
  { name: 'ALABAMA', standard: 'Ala.', postal: 'AL' },
  { name: 'ALASKA', standard: 'Alaska', postal: 'AK' },
  { name: 'ARIZONA', standard: 'Ariz.', postal: 'AZ' },
  { name: 'ARKANSAS', standard: 'Ark.', postal: 'AR' },
  { name: 'CALIFORNIA', standard: 'Calif.', postal: 'CA' },
  { name: 'CANAL ZONE', standard: 'C.Z.', postal: 'CZ' },
  { name: 'COLORADO', standard: 'Colo.', postal: 'CO' },
  { name: 'CONNECTICUT', standard: 'Conn.', postal: 'CT' },
  { name: 'DELAWARE', standard: 'Del.', postal: 'DE' },
  { name: 'DISTRICT OF COLUMBIA', standard: 'D.C.', postal: 'DC' },
  { name: 'FLORIDA', standard: 'Fla.', postal: 'FL' },
  { name: 'GEORGIA', standard: 'Ga.', postal: 'GA' },
  { name: 'GUAM', standard: 'Guam', postal: 'GU' },
  { name: 'HAWAII', standard: 'Hawaii', postal: 'HI' },
  { name: 'IDAHO', standard: 'Idaho', postal: 'ID' },
  { name: 'ILLINOIS', standard: 'Ill.', postal: 'IL' },
  { name: 'INDIANA', standard: 'Ind.', postal: 'IN' },
  { name: 'IOWA', standard: 'Iowa', postal: 'IA' },
  { name: 'KANSAS', standard: 'Kan.', postal: 'KS' },
  { name: 'KENTUCKY', standard: 'Ky.', postal: 'KY' },
  { name: 'LOUISIANA', standard: 'La.', postal: 'LA' },
  { name: 'MAINE', standard: 'Maine', postal: 'ME' },
  { name: 'MARYLAND', standard: 'Md.', postal: 'MD' },
  { name: 'MASSACHUSETTS', standard: 'Mass.', postal: 'MA' },
  { name: 'MICHIGAN', standard: 'Mich.', postal: 'MI' },
  { name: 'MINNESOTA', standard: 'Minn.', postal: 'MN' },
  { name: 'MISSISSIPPI', standard: 'Miss.', postal: 'MS' },
  { name: 'MISSOURI', standard: 'Mo.', postal: 'MO' },
  { name: 'MONTANA', standard: 'Mont.', postal: 'MT' },
  { name: 'NEBRASKA', standard: 'Neb.', postal: 'NE' },
  { name: 'NEVADA', standard: 'Nev.', postal: 'NV' },
  { name: 'NEW HAMPSHIRE', standard: 'N.H.', postal: 'NH' },
  { name: 'NEW JERSEY', standard: 'N.J.', postal: 'NJ' },
  { name: 'NEW MEXICO', standard: 'N.M.', postal: 'NM' },
  { name: 'NEW YORK', standard: 'N.Y.', postal: 'NY' },
  { name: 'NORTH CAROLINA', standard: 'N.C.', postal: 'NC' },
  { name: 'NORTH DAKOTA', standard: 'N.D.', postal: 'ND' },
  { name: 'OHIO', standard: 'Ohio', postal: 'OH' },
  { name: 'OKLAHOMA', standard: 'Okla.', postal: 'OK' },
  { name: 'OREGON', standard: 'Ore.', postal: 'OR' },
  { name: 'PENNSYLVANIA', standard: 'Pa.', postal: 'PA' },
  { name: 'PUERTO RICO', standard: 'P.R.', postal: 'PR' },
  { name: 'RHODE ISLAND', standard: 'R.I.', postal: 'RI' },
  { name: 'SOUTH CAROLINA', standard: 'S.C.', postal: 'SC' },
  { name: 'SOUTH DAKOTA', standard: 'S.D.', postal: 'SD' },
  { name: 'TENNESSEE', standard: 'Tenn.', postal: 'TN' },
  { name: 'TEXAS', standard: 'Texas', postal: 'TX' },
  { name: 'UTAH', standard: 'Utah', postal: 'UT' },
  { name: 'VERMONT', standard: 'Vt.', postal: 'VT' },
  { name: 'VIRGIN ISLANDS', standard: 'V.I.', postal: 'VI' },
  { name: 'VIRGINIA', standard: 'Va.', postal: 'VA' },
  { name: 'WASHINGTON', standard: 'Wash.', postal: 'WA' },
  { name: 'WEST VIRGINIA', standard: 'W.Va.', postal: 'WV' },
  { name: 'WISCONSIN', standard: 'Wis.', postal: 'WI' },
  { name: 'WYOMING', standard: 'Wyo.', postal: 'WY' },
];

export default states;
