const mongoose = require('mongoose');
const { composeMongoose } = require('graphql-compose-mongoose');

const specificlearningdisabilitySchema = new mongoose.Schema({
  LEA_STATE: { type: String, index: true },
  LEA_STATE_NAME: { type: String },
  NCESLEAID: { type: String },
  LEA_NAME: { type: String },
  SCHID: { type: String },
  SCHOOL_NAME: { type: String, index: true },
  COMBOKEY: { type: String },
  JJ: { type: Number },
  DISABILITY_CATEGORY: { type: String },
  AM_M_7: { type: Number },
  AS_M_7: { type: Number },
  BL_M_7: { type: Number },
  HI_M_7: { type: Number },
  MU_M_7: { type: Number },
  PI_M_7: { type: Number },
  WH_M_7: { type: Number },
  AM_F_7: { type: Number },
  AS_F_7: { type: Number },
  BL_F_7: { type: Number },
  HI_F_7: { type: Number },
  MU_F_7: { type: Number },
  PI_F_7: { type: Number },
  WH_F_7: { type: Number },
  TOTAL_STUDENTS_REPORTED: { type: Number },
  SCH_SLD_ENR_HI_M: { type: Number, index: true },
  SCH_ENR_HI_M: { type: Number },
  RI_HI_M_SLD: { type: Number },
  TOT_SLD_WO_HI_M: { type: Number },
  TOT_ENR_WO_HI_M: { type: Number },
  RI_WO_HI_M_SLD: { type: Number },
  RR_HI_M_POP_SLD: { type: Number, index: true },
  RI_WH_M_SLD_1: { type: Number },
  RR_HI_M_WH_M_SLD: { type: Number, index: true },
  SCH_SLD_ENR_HI_F: { type: Number, index: true },
  SCH_ENR_HI_F: { type: Number },
  RI_HI_F_SLD: { type: Number },
  TOT_SLD_WO_HI_F: { type: Number },
  TOT_ENR_WO_HI_F: { type: Number },
  RI_WO_HI_F_SLD: { type: Number },
  RR_HI_F_POP_SLD: { type: Number, index: true },
  RI_WH_F_SLD_2: { type: Number },
  RR_HI_F_WH_F_SLD: { type: Number, index: true },
  SCH_SLD_ENR_AM_M: { type: Number, index: true },
  SCH_ENR_AM_M: { type: Number },
  RI_AM_M_SLD: { type: Number },
  TOT_SLD_WO_AM_M: { type: Number },
  TOT_ENR_WO_AM_M: { type: Number },
  RI_WO_AM_M_SLD: { type: Number },
  RR_AM_M_POP_SLD: { type: Number, index: true },
  RI_WH_M_SLD_3: { type: Number },
  RR_AM_M_WH_M_SLD: { type: Number, index: true },
  SCH_SLD_ENR_AM_F: { type: Number, index: true },
  SCH_ENR_AM_F: { type: Number },
  RI_AM_F_SLD: { type: Number },
  TOT_SLD_WO_AM_F: { type: Number },
  TOT_ENR_WO_AM_F: { type: Number },
  RI_WO_AM_F_SLD: { type: Number },
  RR_AM_F_POP_SLD: { type: Number, index: true },
  RI_WH_F_SLD_4: { type: Number },
  RR_AM_F_WH_F_SLD: { type: Number, index: true },
  SCH_SLD_ENR_AS_M: { type: Number, index: true },
  SCH_ENR_AS_M: { type: Number },
  RI_AS_M_SLD: { type: Number },
  TOT_SLD_WO_AS_M: { type: Number },
  TOT_ENR_WO_AS_M: { type: Number },
  RI_WO_AS_M_SLD: { type: Number },
  RR_AS_M_POP_SLD: { type: Number, index: true },
  RI_WH_M_SLD_5: { type: Number },
  RR_AS_M_WH_M_SLD: { type: Number, index: true },
  SCH_SLD_ENR_AS_F: { type: Number, index: true },
  SCH_ENR_AS_F: { type: Number },
  RI_AS_F_SLD: { type: Number },
  TOT_SLD_WO_AS_F: { type: Number },
  TOT_ENR_WO_AS_F: { type: Number },
  RI_WO_AS_F_SLD: { type: Number },
  RR_AS_F_POP_SLD: { type: Number, index: true },
  RI_WH_F_SLD_6: { type: Number },
  RR_AS_F_WH_F_SLD: { type: Number, index: true },
  SCH_SLD_ENR_HP_M: { type: Number, index: true },
  SCH_ENR_HP_M: { type: Number },
  RI_HP_M_SLD: { type: Number },
  TOT_SLD_WO_HP_M: { type: Number },
  TOT_ENR_WO_HP_M: { type: Number },
  RI_WO_HP_M_SLD: { type: Number },
  RR_HP_M_POP_SLD: { type: Number, index: true },
  RI_WH_M_SLD_7: { type: Number },
  RR_HP_M_WH_M_SLD: { type: Number, index: true },
  SCH_SLD_ENR_HP_F: { type: Number, index: true },
  SCH_ENR_HP_F: { type: Number },
  RI_HP_F_SLD: { type: Number },
  TOT_SLD_WO_HP_F: { type: Number },
  TOT_ENR_WO_HP_F: { type: Number },
  RI_WO_HP_F: { type: Number },
  RR_HP_F_POP_SLD: { type: Number, index: true },
  RI_WH_F_SLD_8: { type: Number },
  RR_HP_F_WH_F_SLD: { type: Number, index: true },
  SCH_SLD_ENR_BL_M: { type: Number, index: true },
  SCH_ENR_BL_M: { type: Number },
  RI_BL_M_SLD: { type: Number },
  TOT_SLD_WO_BL_M: { type: Number },
  TOT_ENR_WO_BL_M: { type: Number },
  RI_WO_BL_M_SLD: { type: Number },
  RR_BL_M_POP_SLD: { type: Number, index: true },
  RI_WH_M_SLD_9: { type: Number },
  RR_BL_M_WH_M_SLD: { type: Number, index: true },
  SCH_SLD_ENR_BL_F: { type: Number, index: true },
  SCH_ENR_BL_F: { type: Number },
  RI_BL_F_SLD: { type: Number },
  TOT_SLD_WO_BL_F: { type: Number },
  TOT_EN_WO_BL_F: { type: Number },
  RI_WO_BL_F_SLD: { type: Number },
  RR_BL_F_POP_SLD: { type: Number, index: true },
  RI_WH_F_SLD_10: { type: Number },
  RR_BL_F_WH_F_SLD: { type: Number, index: true },
  SCH_SLD_ENR_TR_M: { type: Number, index: true },
  SCH_ENR_TR_M: { type: Number },
  RI_TR_M_SLD: { type: Number },
  TOT_SLD_WO_TR_M: { type: Number },
  TOT_ENR_WO_TR_M: { type: Number },
  RI_WO_TR_M_SLD: { type: Number },
  RR_TR_M_POP_SLD: { type: Number, index: true },
  RI_WH_M_SLD_11: { type: Number },
  RR_TR_M_WH_M_SLD: { type: Number, index: true },
  SCH_SLD_ENR_TR_F: { type: Number, index: true },
  SCH_ENR_TR_F: { type: Number },
  RI_TR_F_SLD: { type: Number },
  TOT_SLD_WO_TR_F: { type: Number },
  TOT_ENR_WO_TR_F: { type: Number },
  RI_WO_TR_F_SLD: { type: Number },
  RR_TR_F_POP_SLD: { type: Number, index: true },
  RI_WH_F_SLD_12: { type: Number },
  RR_TR_F_WH_F_SLD: { type: Number, index: true },
  SCH_SLD_ENR_WH_M: { type: Number, index: true },
  SCH_ENR_WH_M: { type: Number },
  RI_WH_M_SLD_13: { type: Number },
  TOT_SLD_WO_WH_M: { type: Number },
  TOT_ENR_WO_WH_M: { type: Number },
  RI_WO_WH_M_SLD: { type: Number },
  RR_WH_M_POP_SLD: { type: Number, index: true },
  SCH_SLD_ENR_WH_F: { type: Number, index: true },
  SCH_ENR_WH_F: { type: Number },
  RI_WH_F_SLD_14: { type: Number },
  TOT_SLD_WO_WH_F: { type: Number },
  TOT_ENR_WO_WH_F: { type: Number },
  RI_WO_WH_F_SLD: { type: Number },
  RR_WH_F_POP_SLD: { type: Number, index: true },
});

const Specificlearningdisability = mongoose.model(
  'Specificlearningdisability',
  specificlearningdisabilitySchema,
);
const SpecificlearningdisabilityTC = composeMongoose(
  Specificlearningdisability,
);

module.exports = { Specificlearningdisability, SpecificlearningdisabilityTC };
